Add robust logging to themectl

diff --git a/scripts/include/themectl/util/color b/scripts/include/themectl/util/color
--- a/scripts/include/themectl/util/color
+++ b/scripts/include/themectl/util/color
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+ID_COLOR="$_ID:util:color"
+
 # This themectl utility pulls color values out of the current theme's 
 # `scheme.json` and prints them (prettily)
 
@@ -11,21 +13,14 @@ L_DELTA_THRESHOLD=70
 # Space between pretty print inline members
 PRETTY_PRINT_PADDING=5
 
-if [ -z $THEME ]; then
-    >&2 echo "No theme detected. Set 'THEME' environment var to your theme name."
-    exit 1
-fi
-if [ ! -f $COLORS_JSON ]; then
-    >&2 echo "scheme.json not found at $THEME_DIR/$THEME"
-    >&2 echo "Does this theme not have a color scheme defined?"
-    exit 1
-fi
+[ -z $THEME ] &&
+    log_error $ID_COLOR "No theme detected. Set THEME before sourcing." && exit 1
+[ ! -f $COLORS_JSON ] &&
+    log_error $ID_COLOR "Required file $COLORS_JSON missing." && exit 1
 
 NO_COLOR=
-if [ ! command -v bc > /dev/null 2>&1 ]; then
-    >&2 echo "WARNING: bc not found. Color output disabled."
-    NO_COLOR=1
-fi
+[ ! command -v bc > /dev/null 2>&1 ] &&
+    log_warn $ID_COLOR "bc not found. Color output disabled." && NO_COLOR=1
 
 # Helper function to calculate perceived luminance, used for colorizing output
 rgb_luminance() {
@@ -38,10 +33,8 @@ rgb_luminance() {
 colorize_hex() {
     local HEX=$1 #e.g. "#012345"
     local HEX_REGEX="^#[0-9|a-f]+$"
-    if [[ ! $HEX =~ $HEX_REGEX ]] || [ $(echo "$HEX" | wc -L) -ne 7 ]; then
-        echo -ne "${HEX}[INVALID]"
-        return 1
-    fi
+    [[ ! $HEX =~ $HEX_REGEX ]] || [ $(echo "$HEX" | wc -L) -ne 7 ] &&
+        echo -ne "${HEX}[INVALID]" && return 1
     local R=$((16#"${HEX:1:2}"))
     local G=$((16#"${HEX:3:2}"))
     local B=$((16#"${HEX:5:2}"))
@@ -52,33 +45,30 @@ colorize_hex() {
     local COL_BG="\\033[48;2"
     local COL_SEQ="${COL_FG};${R};${G};${B}m"
     local COL_CLEAR='\033[0m'
-    if [ ${L_DELTA#-} -lt $L_DELTA_THRESHOLD ]; then
+    [ ${L_DELTA#-} -lt $L_DELTA_THRESHOLD ] &&
         COL_SEQ="${COL_BG};${R};${G};${B}m"
-    fi
     echo -n "${COL_SEQ}${HEX}${COL_CLEAR}"
 }
 
 # Gets hex code from colors.json based on query
 get_color_hex() {
+    local ID="$ID:$ID_COLOR:$FUNCNAME"
     local QUERY=$1
     case $QUERY in
         color*)
             local COLOR_CODE=$(echo "${QUERY#*color}")
-            if [ $COLOR_CODE -gt 15 ] || [ $COLOR_CODE -lt 0 ]; then
-                >&2 echo "Only numeric colors 0-15 are valid."
+            [ $COLOR_CODE -gt 15 ] || [ $COLOR_CODE -lt 0 ] &&
+                log_error $ID "Color code $COLOR_CODE out of range (0-15)" &&
                 return 1
-            fi
             COLOR=$(jq -r .[\"colors\"].$QUERY $COLORS_JSON)
             ;;
         *)
             COLOR=$(jq -r .[\"special\"].$QUERY $COLORS_JSON)
-            if [ "$COLOR" == "null" ]; then
-                >&2 echo "Color not found: $COLOR"
-                return 1; 
-            fi
+            [ "$COLOR" = "null" ] &&
+                log_error $ID "Color not found: $COLOR" && return 1
             ;;
     esac
-    echo "$COLOR"
+    printf "%b" "$COLOR"
 }
 
 # Prints colorized output (or non-colorized, if NO_COLOR is set)
@@ -123,15 +113,12 @@ pretty_print_align_hex() {
     local COLOR_MW=$2
     WIDTH=$(string_width "$COLOR")
     DELTA=$((COLOR_MW - WIDTH))
-    if [[ $DELTA -gt 0 ]]; then
-        local IFS=' '
-        read -ra COLOR_P <<< "$COLOR"
-        echo -n "${COLOR_P[0]}"
-        printf '%*s' "$((DELTA + 1))" ''
-        echo -n "${COLOR_P[1]}"
-    else
-        echo -n "${COLOR}"
-    fi
+    local IFS=' '
+    [[ $DELTA -gt 0 ]] &&
+        read -ra COLOR_P <<< "$COLOR" &&
+        printf "%b%*s%b" "${COLOR_P[0]}" "$((DELTA + 1))" "${COLOR_P[1]}" \
+        ||
+        printf "%b" "${COLOR}"
 }
 
 pretty_print_all() {
@@ -156,9 +143,7 @@ pretty_print_all() {
 
 themecolor() {
     QUERY=$1
-    if [[ "$QUERY" =~ ^[0-9]+$ ]]; then
-        QUERY="color${QUERY}"
-    fi
+    [[ "$QUERY" =~ ^[0-9]+$ ]] && QUERY="color${QUERY}"
     [ -z $NO_COLOR ] && NO_COLOR=$2
     case "$QUERY" in
         "all")
diff --git a/scripts/include/themectl/util/log b/scripts/include/themectl/util/log
--- a/scripts/include/themectl/util/log
+++ b/scripts/include/themectl/util/log
@@ -1,81 +1,80 @@
 #!/usr/bin/env bash
 
 #
-# This themectl utility handles common logging functions.
-# It is probably more convoluted than it needs to be.
+# This `themectl` utility writes logs to stderr
+# Also prints logs via notify-send (libnotify required)
 #
-# `notify-log` | `notify-warn` | `notify-err`
-# Will log to stdout OR stderr and send the log to a notification daemon.
+# `--notify-only` flag will waive printing the log to `stderr`.
 #
-# `notify-debug`
-# Only logs to stdout.
-#
-# Note to self (on stdout logging):
-# Any function returning output through stdout should log with "no_echo":
-# ` notify-log $FUNCNAME "Hello world" no_echo `
-# This applies only to `notify-log` and `notify-debug`
+# Usage:
+# ```bash
+# source $THIS_FILE
+# ...
+# "$SOME_CMD" || log_error $ID "Something went wrong: $?"
+# log_info $ID "Stuff is happening!" --notify-only
+# ```
 #
 
-# Notification daemon commands, change these if using something else
-N_CMD_LOG="  notify-send --urgency=low   "
-N_CMD_WARN=" notify-send --urgency=normal"
-N_CMD_ERR="  notify-send --urgency=normal"
+###############################################################################
+## Configuration ##############################################################
+###############################################################################
 
-ID="themectl"
-SEP=$(perl -E 'say "-" x 35')
+#
+# Default log level (LL)
+#
+LL_DEFAULT=WARN
 
-log_to_stdout() {
-    echo "$ID:$1:$2" "$3"
+#
+# Notification daemon backend commands (empty variable for log level = no-op)
+#
+N_CMDS=(
+    "" # ------------------------------- TRACE - #
+    "" # ------------------------------- DEBUG - #
+    "notify-send --urgency=low" # ------ INFO -- #
+    "notify-send --urgency=normal" #---- WARN -- #
+    "notify-send --urgency=normal" # --- ERROR - #
+    "notify-send --urgency=critical" #-- FATAL - #
+)
+
+###############################################################################
+
+# Use these functions
+log_trace() { __log "TRACE" "$1" "$2" "$3"; }
+log_info()  { __log "INFO"  "$1" "$2" "$3"; }
+log_warn()  { __log "WARN"  "$1" "$2" "$3"; }
+log_error() { __log "ERROR" "$1" "$2" "$3"; }
+log_fatal() { __log "FATAL" "$1" "$2" "$3"; }
+log_debug() { __log "DEBUG" "$1" "$2" "$3"; }
+
+# Log Level
+LL=$LL_DEFAULT
+[ -f "$INCLUDE_DIR/log-level" ] &&
+    echo -n "Polling file for log level..." &&
+    LL=$(cat "$INCLUDE_DIR/log-level") &&
+    echo "set to $LL"
+
+__log_level_value() {
+    local OUT="-1"
+    case $1 in
+        TRACE) OUT=0; ;; DEBUG) OUT=1; ;; INFO) OUT=2 ;;
+        WARN) OUT=3; ;; ERROR) OUT=4; ;; FATAL) OUT=5 ;;
+    esac
+    printf "%b" $OUT
 }
 
-log_to_stderr() {
-    >&2 echo "$ID:$1:$2" "$3"
+__log_filter() {
+    [ $(__log_level_value $LEVEL) -ge $(__log_level_value $LL) ] && return 0
+    return 1
 }
 
 __log() {
-    local FUNC="$1"
-    local LEVEL="$2"
-    local MSG="$3"
-    local NO_ECHO="$4"
-    local HEADER="$ID:$FUNC:$LEVEL"
-    local STREAM=
-    case "$LEVEL" in
-        LOG)
-            STREAM="stdout" && $N_CMD_LOG  "$HEADER" "$MSG"
-            ;;
-        WARN)
-            STREAM="stderr" && $N_CMD_WARN "$HEADER" "$MSG"
-            ;;
-        ERR)
-            STREAM="stderr" && $N_CMD_ERR  "$HEADER" "$MSG"
-            ;;
-        DEBUG)
-            STREAM="stdout"
-            ;;
-    esac
-    [ -z "$NO_ECHO" ] && case "$STREAM" in
-        stdout)
-            echo "$ID:$FUNC:$LEVEL" "$MSG"
-            ;;
-        stderr)
-        >&2 echo "$ID:$FUNC:$LEVEL" "$MSG"
-            ;;
-    esac
-}
-
-notify-log() {
-    __log "$1" "LOG" "$2" "$3"
-}
-
-notify-warn() {
-    __log "$1" "WARN" "$2" "$3"
-}
-
-notify-err() {
-    __log "$1" "ERR" "$2" "$3"
-}
-
-notify-debug() {
-    __log "$1" "DEBUG" "$2" "$3"
+    local LEVEL="$1" && shift && ! __log_filter $LEVEL && return 0
+    local ID="$1" && shift
+    local MSG="$1" && shift
+    local SILENT=$([[ "$@" =~ "--silent " ]] && echo 1)
+    local N_CMD_IDX=$(__log_level_value "$LEVEL")
+    local N_CMD="${N_CMDS[$N_CMD_IDX]}"
+    [ ! -z "$N_CMD" ] && ${N_CMD} "$ID:$LEVEL" "$MSG"
+    [ -z "$SILENT" ] && echo "$ID:$FUNC:$LEVEL |" "$MSG" >&2
 }
 
